services:
  network-deploy-service:
    networks:
      - kirana

  app-servers-base-config:
    extends:
      service: network-deploy-service
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://sahilanower2:Jamesbond007@kirana.v12hc.mongodb.net/?retryWrites=true&w=majority&appName=kirana
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build: .
